<?php

namespace AppBundle\Repository;

/**
 * AdminEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
