<?php

namespace AppBundle\Repository;

/**
 * AnswerChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerChallengeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnswersDesc()
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.description', 'd')
            ->orderBy('a.id', 'desc');

        return $query->getQuery()->getResult();
    }
}
