<?php

namespace AppBundle\Repository;

/**
 * AnswerQuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerQuizzRepository extends \Doctrine\ORM\EntityRepository
{
}
