<?php

namespace AppBundle\Repository;

/**
 * AnswerChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerChallengeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDesc()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }
}
