<?php

namespace AppBundle\Repository;

/**
 * CategoryChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryChallengeRepository extends \Doctrine\ORM\EntityRepository
{
}
