<?php

namespace AppBundle\Repository;

/**
 * DescriptionChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionChallengeRepository extends \Doctrine\ORM\EntityRepository
{
}
