<?php

namespace AppBundle\Repository;

/**
 * informMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class informMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
