<?php

namespace AppBundle\Repository;

/**
 * informMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformMenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDesc()
    {
        return $this->findBy([], ['id' => 'DESC']);
    }
}
