<?php

namespace AppBundle\Repository;

/**
 * QuestionQuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionQuizzRepository extends \Doctrine\ORM\EntityRepository
{
}
