<?php

namespace AppBundle\Repository;

/**
 * QuizzTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
