<?php

namespace AppBundle\Repository;

/**
 * ResourceThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
