<?php

namespace AppBundle\Repository;

/**
 * RessourceThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
