<?php

namespace AppBundle\Repository;

/**
 * trainMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
